spring:

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: auth_service

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    hikari:
      initialization-fail-timeout: -1
      minimum-idle: 0
      idle-timeout: 30000
      max-lifetime: 600000
      keepalive-time: 0

  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

logging:
  level:
    root: INFO
    bdj.hkb.auth_service: INFO


management:
  endpoints:
    web:
      exposure:
        include: health,info

ratelimit:
  policies:
    LOGIN:
      capacity: 5
      refill: 15m
      key-by-ip: true
      key-by-user: true
    SIGNUP:
      capacity: 3
      refill: 1h
      key-by-ip: true
      key-by-user: false
    FORGOT_PASSWORD:
      capacity: 3
      refill: 30m
      key-by-ip: true
      key-by-user: true
    REFRESH_TOKEN:
      capacity: 30
      refill: 15m
      key-by-ip: true
      key-by-user: false